In [427]:
import pandas as pd
import numpy as np
import matplotlib as plt


df = pd.read_csv('../Data/Clean/googleplaystore_clean.csv')
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,10000,Free,0.0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,500000,Free,0.0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,5000000,Free,0.0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,50000000,Free,0.0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,100000,Free,0.0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [428]:
df.shape

(8892, 13)

In [429]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8892 entries, 0 to 8891
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             8892 non-null   str
 1   Category        8892 non-null   str
 2   Rating          8892 non-null   float64
 3   Reviews         8892 non-null   int64
 4   Size            8892 non-null   str
 5   Installs        8892 non-null   int64
 6   Type            8892 non-null   str
 7   Price           8892 non-null   float64
 8   Content Rating  8892 non-null   str
 9   Genres          8892 non-null   str
 10  Last Updated    8892 non-null   str
 11  Current Ver     8892 non-null   str
 12  Android Ver     8892 non-null   str
dtypes: float64(2), int64(2), str(9)
memory usage: 903.2 KB

In [430]:
df.describe()

            Rating       Reviews      Installs        Price
count  8892.000000  8.892000e+03  8.892000e+03  8892.000000
mean      4.187877  4.727764e+05  1.648965e+07     0.963155
std       0.522377  2.905052e+06  8.637600e+07    16.189341
min       1.000000  1.000000e+00  1.000000e+00     0.000000
25%       4.000000  1.640000e+02  1.000000e+04     0.000000
50%       4.300000  4.714500e+03  5.000000e+05     0.000000
75%       4.500000  7.126675e+04  5.000000e+06     0.000000
max       5.000000  7.815831e+07  1.000000e+09   400.000000

In [431]:
df[df['Price'] == 400]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
3749,I'm Rich - Trump Edition,LIFESTYLE,3.6,275,7.3M,10000,Paid,400.0,Everyone,Lifestyle,"May 3, 2018",1.0.1,4.1 and up

In [432]:
df.describe(include=['object','string'])

,App,Category,Size,Type,Content Rating,Genres,Last Updated,Current Ver,Android Ver
count,8892,8892,8892,8892,8892,8892,8892,8892,8892
unique,8196,33,414,2,6,115,1300,2638,31
top,ROBLOX,FAMILY,Varies with device,Free,Everyone,Tools,"August 3, 2018",Varies with device,4.1 and up
freq,9,1718,1468,8279,7095,733,291,1262,1989

In [433]:
df['Category'].value_counts().head(10)

Category
FAMILY             1718
GAME               1074
TOOLS               734
PRODUCTIVITY        334
FINANCE             317
PERSONALIZATION     310
COMMUNICATION       307
LIFESTYLE           305
PHOTOGRAPHY         304
MEDICAL             302
Name: count, dtype: int64

In [434]:
df['Type'].value_counts()

Type
Free    8279
Paid     613
Name: count, dtype: int64

In [435]:
df['Content Rating'].value_counts()

Content Rating
Everyone           7095
Teen               1022
Mature 17+          411
Everyone 10+        360
Adults only 18+       3
Unrated               1
Name: count, dtype: int64

In [436]:
category_avg_installs = (
  df.groupby('Category')['Installs']
  .mean()
  .sort_values(ascending=False)
)

print(category_avg_installs.head(10))

Category
COMMUNICATION         7.867180e+07
SOCIAL                5.128624e+07
VIDEO_PLAYERS         3.888686e+07
PRODUCTIVITY          3.731458e+07
PHOTOGRAPHY           3.197777e+07
TRAVEL_AND_LOCAL      3.103346e+07
GAME                  2.937045e+07
NEWS_AND_MAGAZINES    2.520145e+07
ENTERTAINMENT         2.212306e+07
TOOLS                 1.560044e+07
Name: Installs, dtype: float64

In [437]:
#df['Category'].value_counts()['GAME']
#df['Category'].value_counts()['COMMUNICATION']

In [438]:
df.groupby('Type')['Installs'].sum()

Type
Free    146556738856
Paid        69212482
Name: Installs, dtype: int64

In [439]:
df[['Installs', 'Rating']].corr(numeric_only=True)

          Installs    Rating
Installs  1.000000  0.050886
Rating    0.050886  1.000000

In [440]:
df[['Installs', 'Price']].corr(numeric_only=True)

          Installs     Price
Installs  1.000000 -0.011329
Price    -0.011329  1.000000

In [442]:
df.sort_values('Installs', ascending=False).head(10)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
3306,Subway Surfers,GAME,4.5,27711703,76M,1000000000,Free,0.0,Everyone 10+,Arcade,"July 12, 2018",1.90.0,4.1 and up
3550,Hangouts,COMMUNICATION,4.0,3419464,Varies with device,1000000000,Free,0.0,Everyone,Communication,"July 21, 2018",Varies with device,Varies with device
3547,Google,TOOLS,4.4,8021623,Varies with device,1000000000,Free,0.0,Everyone,Tools,"August 3, 2018",Varies with device,Varies with device
3314,WhatsApp Messenger,COMMUNICATION,4.4,69109672,Varies with device,1000000000,Free,0.0,Everyone,Communication,"August 3, 2018",Varies with device,Varies with device
3227,Google News,NEWS_AND_MAGAZINES,3.9,877643,13M,1000000000,Free,0.0,Teen,News & Magazines,"August 1, 2018",5.2.0,4.4 and up
2599,Google Street View,TRAVEL_AND_LOCAL,4.2,2129689,Varies with device,1000000000,Free,0.0,Everyone,Travel & Local,"August 6, 2018",Varies with device,Varies with device
3319,Instagram,SOCIAL,4.5,66509917,Varies with device,1000000000,Free,0.0,Teen,Social,"July 31, 2018",Varies with device,Varies with device
1367,Subway Surfers,GAME,4.5,27722264,76M,1000000000,Free,0.0,Everyone 10+,Arcade,"July 12, 2018",1.90.0,4.1 and up
3541,Google+,SOCIAL,4.2,4828372,Varies with device,1000000000,Free,0.0,Teen,Social,"July 26, 2018",Varies with device,Varies with device
2968,Google Drive,PRODUCTIVITY,4.4,2731211,Varies with device,1000000000,Free,0.0,Everyone,Productivity,"August 6, 2018",Varies with device,Varies with device

In [450]:
df[df['Category'] == 'GAME'].sort_values('Installs', ascending=False).head(10)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
1413,Subway Surfers,GAME,4.5,27723193,76M,1000000000,Free,0.0,Everyone 10+,Arcade,"July 12, 2018",1.90.0,4.1 and up
1367,Subway Surfers,GAME,4.5,27722264,76M,1000000000,Free,0.0,Everyone 10+,Arcade,"July 12, 2018",1.90.0,4.1 and up
1460,Subway Surfers,GAME,4.5,27724094,76M,1000000000,Free,0.0,Everyone 10+,Arcade,"July 12, 2018",1.90.0,4.1 and up
1575,Subway Surfers,GAME,4.5,27725352,76M,1000000000,Free,0.0,Everyone 10+,Arcade,"July 12, 2018",1.90.0,4.1 and up
3306,Subway Surfers,GAME,4.5,27711703,76M,1000000000,Free,0.0,Everyone 10+,Arcade,"July 12, 2018",1.90.0,4.1 and up
1417,Candy Crush Saga,GAME,4.4,22428456,74M,500000000,Free,0.0,Everyone,Casual,"July 5, 2018",1.129.0.2,4.1 and up
1433,My Talking Tom,GAME,4.5,14891223,Varies with device,500000000,Free,0.0,Everyone,Casual,"July 19, 2018",4.8.0.132,4.1 and up
1368,Candy Crush Saga,GAME,4.4,22426677,74M,500000000,Free,0.0,Everyone,Casual,"July 5, 2018",1.129.0.2,4.1 and up
1439,Temple Run 2,GAME,4.3,8118937,62M,500000000,Free,0.0,Everyone,Action,"July 5, 2018",1.49.1,4.0 and up
3446,Temple Run 2,GAME,4.3,8116142,62M,500000000,Free,0.0,Everyone,Action,"July 5, 2018",1.49.1,4.0 and up

In [451]:
df[df['Category'] == 'COMMUNICATION'].sort_values('Installs', ascending=False).head(10)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
336,Messenger – Text and Video Chat for Free,COMMUNICATION,4.0,56646578,Varies with device,1000000000,Free,0.0,Everyone,Communication,"August 1, 2018",Varies with device,Varies with device
340,Hangouts,COMMUNICATION,4.0,3419433,Varies with device,1000000000,Free,0.0,Everyone,Communication,"July 21, 2018",Varies with device,Varies with device
363,Google Chrome: Fast & Secure,COMMUNICATION,4.3,9643041,Varies with device,1000000000,Free,0.0,Everyone,Communication,"August 1, 2018",Varies with device,Varies with device
345,Skype - free IM & video calls,COMMUNICATION,4.1,10484169,Varies with device,1000000000,Free,0.0,Everyone,Communication,"August 3, 2018",Varies with device,Varies with device
3314,WhatsApp Messenger,COMMUNICATION,4.4,69109672,Varies with device,1000000000,Free,0.0,Everyone,Communication,"August 3, 2018",Varies with device,Varies with device
3402,Google Chrome: Fast & Secure,COMMUNICATION,4.3,9642112,Varies with device,1000000000,Free,0.0,Everyone,Communication,"August 1, 2018",Varies with device,Varies with device
290,Messenger – Text and Video Chat for Free,COMMUNICATION,4.0,56642847,Varies with device,1000000000,Free,0.0,Everyone,Communication,"August 1, 2018",Varies with device,Varies with device
295,Gmail,COMMUNICATION,4.3,4604324,Varies with device,1000000000,Free,0.0,Everyone,Communication,"August 2, 2018",Varies with device,Varies with device
291,WhatsApp Messenger,COMMUNICATION,4.4,69119316,Varies with device,1000000000,Free,0.0,Everyone,Communication,"August 3, 2018",Varies with device,Varies with device
400,Gmail,COMMUNICATION,4.3,4604483,Varies with device,1000000000,Free,0.0,Everyone,Communication,"August 2, 2018",Varies with device,Varies with device